version: 0.2

phases:
  install:
    commands:
      - cd projects/cloud-support-engineer-projects/project-2/frontend
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - projects/cloud-support-engineer-projects/project-2/frontend/build/**/*
