version: 0.2

phases:
  install:
    commands:
      - cd frontend
      - npm install

  build:
    commands:
      - cd frontend
      - npm run build

artifacts:
  base-directory: frontend/build
  files:
    - '**/*'
version: 0.2
