version: 0.2

phases:
  install:
    commands:
      - cd projects/cloud-support-engineer-projects/project-2/frontend
      - npm install

  build:
    commands:
      - npm run build
      - cd ..

artifacts:
  base-directory: projects/cloud-support-engineer-projects/project-2
  files:
    - appspec.yml
    - scripts/**/*
    - frontend/build/**/*
